services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cine-admin-api
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=production # Removed extra space
    ports:
      - '${PORT}:3000'
    networks:
      - cine-admin-network


networks:
  cine-admin-network:
    driver: bridge


